/*
ERD Notes:

ADM_CODE -> ADM_CODE_ITEM (1-to-many)
ADM_LOCATION -> SC_USER, SC_PATIENT (1-to-many)
SC_PATIENT -> SC_ANEMIA_CHECKUP (1-to-many)
SC_ANEMIA_CHECKUP -> SC_ANEMIA_PERFORMA (1-to-many)
SC_PATIENT -> SC_DELIVERY (1-to-many)
SC_DELIVERY -> SC_SIX_WEEK_POSTNATAL_CHECKUP (1-to-many)
SC_DELIVERY -> SC_ANNUAL_POSTNATAL_CHECKUP (1-to-many)
Soft delete:

All tables include IS_DELETED BIT DEFAULT 0.
Recommended practice: never DELETE rows; instead UPDATE IS_DELETED=1.
*/

-- Use a consistent SQL mode for predictable behavior.
SET SQL_MODE = 'STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,ONLY_FULL_GROUP_BY';

-- 1) CREATE DATABASE + USE

CREATE DATABASE IF NOT EXISTS SAKINA_CARE
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE SAKINA_CARE;

-- 2) Common defaults / helper comments

-- Common columns required in ALL tables: -- IS_DELETED BIT DEFAULT 0, -- ADDED_BY BIGINT, -- UPDATED_BY BIGINT, -- DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP, -- DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP
-- Note: MySQL cannot assign UPDATED_TIMESTAMP automatically via DEFAULT only.
-- We keep the requirement exactly as requested (DEFAULT CURRENT_TIMESTAMP).
-- If you want automatic updates on UPDATE, add a trigger (see optimization section).

-- 3) TABLE: ADM_CODE

DROP TABLE IF EXISTS SC_ANNUAL_POSTNATAL_CHECKUP;
DROP TABLE IF EXISTS SC_SIX_WEEK_POSTNATAL_CHECKUP;
DROP TABLE IF EXISTS SC_DELIVERY;
DROP TABLE IF EXISTS SC_ANEMIA_PERFORMA;
DROP TABLE IF EXISTS SC_ANEMIA_CHECKUP;
DROP TABLE IF EXISTS SC_PATIENT;
DROP TABLE IF EXISTS SC_USER;
DROP TABLE IF EXISTS ADM_CODE_ITEM;
DROP TABLE IF EXISTS ADM_CODE;
DROP TABLE IF EXISTS ADM_LOCATION;

CREATE TABLE IF NOT EXISTS ADM_CODE (
CODE_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CODE_NAME NVARCHAR(255) NULL,
CODE_DESCRIPTION NVARCHAR(500) NULL,

PRIMARY KEY (CODE_ID)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Master codes for the application';

-- 4) TABLE: ADM_CODE_ITEM

CREATE TABLE IF NOT EXISTS ADM_CODE_ITEM (
CODE_ITEM_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

CODE_ID BIGINT NOT NULL,
ITEM_NAME NVARCHAR(255) NULL,
ITEM_VALUE NVARCHAR(255) NULL,

PRIMARY KEY (CODE_ITEM_ID),
CONSTRAINT fk_adm_code_item_code
FOREIGN KEY (CODE_ID)
REFERENCES ADM_CODE (CODE_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Items belonging to ADM_CODE';

-- 5) TABLE: ADM_LOCATION

CREATE TABLE IF NOT EXISTS ADM_LOCATION (
LOCATION_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

LOCATION_NAME NVARCHAR(255) NULL,

PRIMARY KEY (LOCATION_ID)
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Locations/regions for patient and users';

-- 6) TABLE: SC_USER

CREATE TABLE IF NOT EXISTS SC_USER (
USER_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

EMAIL NVARCHAR(250) NOT NULL,
PASS NVARCHAR(250) NULL,
USER_ROLE NVARCHAR(100) NULL,
LOCATION_ID BIGINT NULL,
FIRSTNAME NVARCHAR(150) NULL,
LASTNAME NVARCHAR(150) NULL,
CONTACT NVARCHAR(50) NULL,
ADDRESS NVARCHAR(500) NULL,
PROFILE_PICTURE_URL NVARCHAR(500) NULL,

PRIMARY KEY (USER_ID),
UNIQUE KEY uq_sc_user_email (EMAIL),
CONSTRAINT fk_sc_user_location
FOREIGN KEY (LOCATION_ID)
REFERENCES ADM_LOCATION (LOCATION_ID)
ON DELETE SET NULL
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Application users';

-- 7) TABLE: SC_PATIENT

CREATE TABLE IF NOT EXISTS SC_PATIENT (
PATIENT_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

PATIENT_NAME NVARCHAR(255) NULL,
CNIC_NUMBER NVARCHAR(50) NULL,
PHONE_NUMBER NVARCHAR(50) NULL,
LOCATION_ID BIGINT NULL,

PRIMARY KEY (PATIENT_ID),
CONSTRAINT fk_sc_patient_location
FOREIGN KEY (LOCATION_ID)
REFERENCES ADM_LOCATION (LOCATION_ID)
ON DELETE SET NULL
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Patients registered in the system';

-- Recommended additional constraint (optional but practical): CNIC uniqueness
-- If you want strict uniqueness, uncomment the following line.
-- ALTER TABLE SC_PATIENT ADD UNIQUE KEY uq_sc_patient_cnic (CNIC_NUMBER);

-- 8) TABLE: SC_ANEMIA_CHECKUP

CREATE TABLE IF NOT EXISTS SC_ANEMIA_CHECKUP (
ANEMIA_CHECKUP_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

PATIENT_ID BIGINT NOT NULL,

PRIMARY KEY (ANEMIA_CHECKUP_ID),
CONSTRAINT fk_sc_anemia_checkup_patient
FOREIGN KEY (PATIENT_ID)
REFERENCES SC_PATIENT (PATIENT_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Anemia checkups taken by patients';

-- 9) TABLE: SC_ANEMIA_PERFORMA

CREATE TABLE IF NOT EXISTS SC_ANEMIA_PERFORMA (
ANEMIA_PERFORMA_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

ANEMIA_CHECKUP_ID BIGINT NOT NULL,

PRIMARY KEY (ANEMIA_PERFORMA_ID),
CONSTRAINT fk_sc_anemia_performa_checkup
FOREIGN KEY (ANEMIA_CHECKUP_ID)
REFERENCES SC_ANEMIA_CHECKUP (ANEMIA_CHECKUP_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Anemia performa records for a checkup';

-- 10) TABLE: SC_DELIVERY

CREATE TABLE IF NOT EXISTS SC_DELIVERY (
DELIVERY_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

PATIENT_ID BIGINT NOT NULL,

PRIMARY KEY (DELIVERY_ID),
CONSTRAINT fk_sc_delivery_patient
FOREIGN KEY (PATIENT_ID)
REFERENCES SC_PATIENT (PATIENT_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Deliveries associated with patients';

-- 11) TABLE: SC_SIX_WEEK_POSTNATAL_CHECKUP

CREATE TABLE IF NOT EXISTS SC_SIX_WEEK_POSTNATAL_CHECKUP (
SIX_WEEK_CHECKUP_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

DELIVERY_ID BIGINT NOT NULL,

PRIMARY KEY (SIX_WEEK_CHECKUP_ID),
CONSTRAINT fk_sc_six_week_checkup_delivery
FOREIGN KEY (DELIVERY_ID)
REFERENCES SC_DELIVERY (DELIVERY_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Six-week postnatal checkups after delivery';

-- 12) TABLE: SC_ANNUAL_POSTNATAL_CHECKUP

CREATE TABLE IF NOT EXISTS SC_ANNUAL_POSTNATAL_CHECKUP (
ANNUAL_CHECKUP_ID BIGINT NOT NULL AUTO_INCREMENT,
IS_DELETED BIT NOT NULL DEFAULT b'0',
ADDED_BY BIGINT NULL,
UPDATED_BY BIGINT NULL,
DATE_CREATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

DELIVERY_ID BIGINT NOT NULL,

PRIMARY KEY (ANNUAL_CHECKUP_ID),
CONSTRAINT fk_sc_annual_checkup_delivery
FOREIGN KEY (DELIVERY_ID)
REFERENCES SC_DELIVERY (DELIVERY_ID)
ON DELETE RESTRICT
ON UPDATE CASCADE
) ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci
COMMENT='Annual postnatal checkups after delivery';

-- 13) INDEXES (explicit CREATE INDEX statements)

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_adm_code_item_code_id
ON ADM_CODE_ITEM (CODE_ID);

CREATE INDEX IF NOT EXISTS idx_sc_user_location_id
ON SC_USER (LOCATION_ID);

CREATE INDEX IF NOT EXISTS idx_sc_patient_location_id
ON SC_PATIENT (LOCATION_ID);

CREATE INDEX IF NOT EXISTS idx_sc_anemia_checkup_patient_id
ON SC_ANEMIA_CHECKUP (PATIENT_ID);

CREATE INDEX IF NOT EXISTS idx_sc_anemia_performa_checkup_id
ON SC_ANEMIA_PERFORMA (ANEMIA_CHECKUP_ID);

CREATE INDEX IF NOT EXISTS idx_sc_delivery_patient_id
ON SC_DELIVERY (PATIENT_ID);

CREATE INDEX IF NOT EXISTS idx_sc_six_week_checkup_delivery_id
ON SC_SIX_WEEK_POSTNATAL_CHECKUP (DELIVERY_ID);

CREATE INDEX IF NOT EXISTS idx_sc_annual_checkup_delivery_id
ON SC_ANNUAL_POSTNATAL_CHECKUP (DELIVERY_ID);

-- Soft delete helper indexes (commonly used to filter active rows)
CREATE INDEX IF NOT EXISTS idx_adm_code_is_deleted ON ADM_CODE (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_adm_code_item_is_deleted ON ADM_CODE_ITEM (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_adm_location_is_deleted ON ADM_LOCATION (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_user_is_deleted ON SC_USER (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_patient_is_deleted ON SC_PATIENT (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_anemia_checkup_is_deleted ON SC_ANEMIA_CHECKUP (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_anemia_performa_is_deleted ON SC_ANEMIA_PERFORMA (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_delivery_is_deleted ON SC_DELIVERY (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_six_week_checkup_is_deleted ON SC_SIX_WEEK_POSTNATAL_CHECKUP (IS_DELETED);
CREATE INDEX IF NOT EXISTS idx_sc_annual_checkup_is_deleted ON SC_ANNUAL_POSTNATAL_CHECKUP (IS_DELETED);

-- 14) SAMPLE INSERTS (testing)

-- Insert ADM_LOCATION
INSERT INTO ADM_LOCATION (
IS_DELETED, ADDED_BY, UPDATED_BY, LOCATION_NAME
) VALUES
(b'0', 1, 1, 'Karachi');

-- Insert ADM_CODE and ADM_CODE_ITEM
INSERT INTO ADM_CODE (
IS_DELETED, ADDED_BY, UPDATED_BY, CODE_NAME, CODE_DESCRIPTION
) VALUES
(b'0', 1, 1, 'BLOOD_GROUP', 'Example blood group codes');

INSERT INTO ADM_CODE_ITEM (
IS_DELETED, ADDED_BY, UPDATED_BY, CODE_ID, ITEM_NAME, ITEM_VALUE
) VALUES
(b'0', 1, 1, (SELECT CODE_ID FROM ADM_CODE WHERE CODE_NAME='BLOOD_GROUP' LIMIT 1), 'A+', 'A+'),
(b'0', 1, 1, (SELECT CODE_ID FROM ADM_CODE WHERE CODE_NAME='BLOOD_GROUP' LIMIT 1), 'O+', 'O+');

-- Insert SC_USER
INSERT INTO SC_USER (
IS_DELETED, ADDED_BY, UPDATED_BY,
EMAIL, PASS, USER_ROLE, LOCATION_ID,
FIRSTNAME, LASTNAME, CONTACT, ADDRESS, PROFILE_PICTURE_URL
) VALUES
(b'0', 1, 1,
'doctor@example.com', 'hashed_password_here', 'DOCTOR',
(SELECT LOCATION_ID FROM ADM_LOCATION WHERE LOCATION_NAME='Karachi' LIMIT 1),
'Sara', 'Khan', '03001234567', 'Street 1, Karachi', 'https://example.com/profile1.png'
);

-- Insert SC_PATIENT
INSERT INTO SC_PATIENT (
IS_DELETED, ADDED_BY, UPDATED_BY,
PATIENT_NAME, CNIC_NUMBER, PHONE_NUMBER, LOCATION_ID
) VALUES
(b'0', 1, 1,
'Ayesha Noor', '35202-1234567-1', '03111222333',
(SELECT LOCATION_ID FROM ADM_LOCATION WHERE LOCATION_NAME='Karachi' LIMIT 1)
);

-- Insert SC_ANEMIA_CHECKUP
INSERT INTO SC_ANEMIA_CHECKUP (
IS_DELETED, ADDED_BY, UPDATED_BY, PATIENT_ID
) VALUES
(b'0', 1, 1, (SELECT PATIENT_ID FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor' LIMIT 1));

-- Insert SC_ANEMIA_PERFORMA
INSERT INTO SC_ANEMIA_PERFORMA (
IS_DELETED, ADDED_BY, UPDATED_BY, ANEMIA_CHECKUP_ID
) VALUES
(b'0', 1, 1, (SELECT ANEMIA_CHECKUP_ID FROM SC_ANEMIA_CHECKUP WHERE PATIENT_ID = (SELECT PATIENT_ID FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor' LIMIT 1) ORDER BY ANEMIA_CHECKUP_ID DESC LIMIT 1));

-- Insert SC_DELIVERY
INSERT INTO SC_DELIVERY (
IS_DELETED, ADDED_BY, UPDATED_BY, PATIENT_ID
) VALUES
(b'0', 1, 1, (SELECT PATIENT_ID FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor' LIMIT 1));

-- Insert SC_SIX_WEEK_POSTNATAL_CHECKUP
INSERT INTO SC_SIX_WEEK_POSTNATAL_CHECKUP (
IS_DELETED, ADDED_BY, UPDATED_BY, DELIVERY_ID
) VALUES
(b'0', 1, 1, (SELECT DELIVERY_ID FROM SC_DELIVERY WHERE PATIENT_ID = (SELECT PATIENT_ID FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor' LIMIT 1) ORDER BY DELIVERY_ID DESC LIMIT 1));

-- Insert SC_ANNUAL_POSTNATAL_CHECKUP
INSERT INTO SC_ANNUAL_POSTNATAL_CHECKUP (
IS_DELETED, ADDED_BY, UPDATED_BY, DELIVERY_ID
) VALUES
(b'0', 1, 1, (SELECT DELIVERY_ID FROM SC_DELIVERY WHERE PATIENT_ID = (SELECT PATIENT_ID FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor' LIMIT 1) ORDER BY DELIVERY_ID DESC LIMIT 1));

-- 15) TEST QUERIES

-- 15.1 Verify inserted rows
SELECT * FROM ADM_LOCATION;
SELECT * FROM ADM_CODE;
SELECT * FROM ADM_CODE_ITEM;
SELECT * FROM SC_USER;
SELECT * FROM SC_PATIENT;
SELECT * FROM SC_ANEMIA_CHECKUP;
SELECT * FROM SC_ANEMIA_PERFORMA;
SELECT * FROM SC_DELIVERY;
SELECT * FROM SC_SIX_WEEK_POSTNATAL_CHECKUP;
SELECT * FROM SC_ANNUAL_POSTNATAL_CHECKUP;

-- 15.2 Join check (patient -> anemia checkups -> performa)
SELECT
p.PATIENT_ID,
p.PATIENT_NAME,
a.ANEMIA_CHECKUP_ID,
ap.ANEMIA_PERFORMA_ID
FROM SC_PATIENT p
JOIN SC_ANEMIA_CHECKUP a
ON a.PATIENT_ID = p.PATIENT_ID
JOIN SC_ANEMIA_PERFORMA ap
ON ap.ANEMIA_CHECKUP_ID = a.ANEMIA_CHECKUP_ID
WHERE p.IS_DELETED = b'0'
AND a.IS_DELETED = b'0'
AND ap.IS_DELETED = b'0'
ORDER BY p.PATIENT_ID DESC, a.ANEMIA_CHECKUP_ID DESC;

-- 15.3 Soft delete pattern (mark as deleted)
UPDATE SC_PATIENT
SET IS_DELETED = b'1', UPDATED_BY = 1
WHERE PATIENT_NAME = 'Ayesha Noor';

-- Confirm soft-deleted row remains but would be excluded by queries filtering IS_DELETED
SELECT *
FROM SC_PATIENT
WHERE PATIENT_NAME = 'Ayesha Noor';

-- 15.4 FK constraint behavior (should fail if you try to delete restricted parent) -- This should fail due to ON DELETE RESTRICT. -- Uncomment to test.
-- DELETE FROM SC_PATIENT WHERE PATIENT_NAME='Ayesha Noor';

-- 16) ON DELETE / ON UPDATE Rules Summary

-- -- ADM_CODE_ITEM.CODE_ID -> ADM_CODE.CODE_ID -- ON DELETE RESTRICT, ON UPDATE CASCADE
-- SC_USER.LOCATION_ID -> ADM_LOCATION.LOCATION_ID -- ON DELETE SET NULL, ON UPDATE CASCADE
-- SC_PATIENT.LOCATION_ID -> ADM_LOCATION.LOCATION_ID -- ON DELETE SET NULL, ON UPDATE CASCADE
-- SC_ANEMIA_CHECKUP.PATIENT_ID -> SC_PATIENT.PATIENT_ID -- ON DELETE RESTRICT, ON UPDATE CASCADE
-- SC_ANEMIA_PERFORMA.ANEMIA_CHECKUP_ID -> SC_ANEMIA_CHECKUP.ANEMIA_CHECKUP_ID -- ON DELETE RESTRICT, ON UPDATE CASCADE
-- SC_DELIVERY.PATIENT_ID -> SC_PATIENT.PATIENT_ID -- ON DELETE RESTRICT, ON UPDATE CASCADE
-- SC_SIX_WEEK_POSTNATAL_CHECKUP.DELIVERY_ID -> SC_DELIVERY.DELIVERY_ID -- ON DELETE RESTRICT, ON UPDATE CASCADE
-- SC_ANNUAL_POSTNATAL_CHECKUP.DELIVERY_ID -> SC_DELIVERY.DELIVERY_ID
--   ON DELETE RESTRICT, ON UPDATE CASCADE

-- 17) Database Optimization Suggestions (comments)

/*

Auto-update DATE_UPDATED:
Add triggers per table to set DATE_UPDATED = NOW() on UPDATE.

Composite indexes for soft delete + FK filters:
If your queries often use (IS_DELETED, ), consider composite indexes.
Example:
CREATE INDEX idx_sc_patient_is_deleted_location ON SC_PATIENT(IS_DELETED, LOCATION_ID);

Consider additional natural unique constraints:
Example: UNIQUE(CNIC_NUMBER) on SC_PATIENT if business rules allow.

Use proper row sizes:
NVARCHAR columns store utf8mb4; keep lengths tight to avoid large row overhead.

Use migrations:
Run this script via migrations for repeatable environments.

*/