-- Run this SQL on your MySQL server (adjust root credentials externally).

CREATE DATABASE IF NOT EXISTS SAKINACARE;

USE SAKINACARE;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

