CREATE TABLE ADM_CODE (
CODE_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
CODE_NAME VARCHAR(255),
CODE_DESCRIPTION VARCHAR(500),

IS_DELETED BIT DEFAULT 0,
ADDED_BY BIGINT,
UPDATED_BY BIGINT,
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE ADM_CODE_ITEM (
CODE_ITEM_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
CODE_ID BIGINT, (Reference from ADM_CODE)
ITEM_NAME VARCHAR(255),
ITEM_VALUE VARCHAR(255),
DISPLAY_ORDER INT,

IS_DELETED BIT DEFAULT 0,
ADDED_BY BIGINT,
UPDATED_BY BIGINT,
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE ADM_USER (
USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ACCOUNT_GUID VARCHAR(30),
EMAIL_ADDRESS VARCHAR(250) UNIQUE NOT NULL,
PASS VARCHAR(250) NOT NULL,
ROLE_ID BIGINT, (Reference from ADM_CODE_ITEM)
LOCATION_ID BIGINT, (Reference from ADM_CODE_ITEM)
FIRST_NAME VARCHAR(150),
LAST_NAME VARCHAR(150),
PHONE_NUMBER VARCHAR(50),
ADDRESS_LINE1 VARCHAR(1000),
ADDRESS_LINE2 VARCHAR(1000),
PROFILE_PICTURE_URL VARCHAR(500),
IS_ACTIVE BIT DEFAULT 1,

IS_DELETED BIT DEFAULT 0,
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE SC_PATIENT (
PATIENT_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
PATIENT_REGISTRATION_NUMBER VARCHAR(100),
REGISTRATION_DATE DATETIME,
PATIENT_NAME VARCHAR(500),
CNIC_NUMBER VARCHAR(50),
PHONE_NUMBER VARCHAR(50),
AGE BIGINT, (Reference from ADM_CODE_ITEM)
HUSBAND_NAME VARCHAR(500),
ADDRESS_LINE1 VARCHAR(8000),
ADDRESS_LINE2 VARCHAR(8000),
RELIGION BIGINT, (Reference from ADM_CODE_ITEM)
LOCATION_ID BIGINT, (Reference from ADM_CODE_ITEM)
EDUCATION BIGINT, (Reference from ADM_CODE_ITEM)
ESTIMATED_DATE_OF_DELIVERY DATETIME,
BASELINE_HAEMOGLOBIN_COUNT DECIMAL(5,2),
PATIENT_PROFESSION VARCHAR(255),
PATIENT_MONTHLY_SALARY VARCHAR(100),
RESIDENCE_CONDITION BIGINT, (Reference from ADM_CODE_ITEM)
RESIDENCE_OWNERSHIP BIGINT, (Reference from ADM_CODE_ITEM)
GRAVIDA INT,
PARA INT,
MISCARRIAGE INT,
ANTENATAL_VISITS INT,
DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);



CREATE TABLE SC_ANEMIA_CHECKUP (
ANEMIA_CHECKUP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID BIGINT, (Reference from SC_DELIVERY)
CHECKUP_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
HAEMOGLOBIN_COUNT DECIMAL(5,2),
ANY_OTHER_SYMPTOMS VARCHAR(8000),

DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE SC_ANEMIA_PERFORMA (
ANEMIA_PERFORMA_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
ANEMIA_CHECKUP_ID BIGINT, (Reference from SC_ANEMIA_CHECKUP)
INJECTION_BRAND BIGINT, (Reference from ADM_CODE_ITEM)
INJECTION_DOSE BIGINT, (Reference from ADM_CODE_ITEM)
IV_IRON_QUANTITY BIGINT, (Reference from ADM_CODE_ITEM)
INJECTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
REACTION_AFTER_INJECTION VARCHAR(8000),

DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE SC_DELIVERY (
DELIVERY_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
PATIENT_ID BIGINT, (Reference from SC_PATIENT)
DELIVERY_CENTRE BIGINT, (Reference from ADM_CODE_ITEM)
DATE_OF_DELIVERY DATETIME,
MODE_OF_DELIVERY BIGINT, (Reference from ADM_CODE_ITEM)
BLOOD_LOSS_DURING_DELIVERY BIGINT, (Reference from ADM_CODE_ITEM)
IS_BABY_ALIVE BIT,
BABY_DEATH_REASON VARCHAR(8000),
IS_MOTHER_ALIVE BIT,
MOTHER_DEATH_REASON VARCHAR(8000),
PREGNANCY_PERIOD_WEEKS BIGINT, (Reference from ADM_CODE_ITEM)
PREGNANCY_PERIOD_DAYS BIGINT, (Reference from ADM_CODE_ITEM)
IS_BREAST_FEED_DURING_FIRST_HOUR BIT,
IS_COLOSTRUM_BREASTMILK_GIVEN BIT,
IS_KANGAROO_CARE BIT,
FEEDBACK_ON_CBK VARCHAR(8000),
FOLLOW_UP_DATE DATETIME,
ANTENATAL_VISITS INT,

DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE SC_SIX_WEEK_POSTNATAL_CHECKUP (
SIX_WEEK_CHECKUP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
DELIVERY_ID BIGINT, (Reference from SC_DELIVERY)
IS_PATIENT_ALIVE BIT,
PATIENT_DEATH_REASON VARCHAR(255),
IS_PATIENT_HEALTHY BIT,
PATIENT_HEALTH_MORE_DETAILS VARCHAR(8000),
IS_BABY_ALIVE BIT,
BABY_DEATH_REASON VARCHAR(8000),
IS_BABY_HEALTHY BIT,
BABY_HEALTH_MORE_DETAILS VARCHAR(8000),
BREAST_FEEDING_DURATION BIGINT, (Reference from ADM_CODE_ITEM)
IS_BABY_CORD_HEALTHY BIT,
BABY_CORD_CONDITION_MORE_DETAILS VARCHAR(8000),
FOLLOWUP_DATE DATETIME,

DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);


CREATE TABLE SC_ANNUAL_POSTNATAL_CHECKUP (
ANNUAL_CHECKUP_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
DELIVERY_ID BIGINT, (Reference from SC_DELIVERY)
IS_PATIENT_ALIVE BIT,
PATIENT_DEATH_REASON VARCHAR(255),
IS_PATIENT_HEALTHY BIT,
PATIENT_HEALTH_MORE_DETAILS VARCHAR(8000),
IS_BABY_ALIVE BIT,
BABY_DEATH_REASON VARCHAR(8000),
IS_BABY_HEALTHY BIT,
BABY_HEALTH_MORE_DETAILS VARCHAR(8000),
IS_BREAST_FEEDING BIT,
BREAST_FEEDING_DURATION BIGINT, (Reference from ADM_CODE_ITEM)
BIRTH_SPACING_PRACTICES BIGINT, (Reference from ADM_CODE_ITEM)

DATA_SOURCE VARCHAR(5), (Possible values are APP or WEB)
IS_DELETED BIT DEFAULT 0,
CREATED_BY_LATITUDE DECIMAL(10,7),
CREATED_BY_LONGITUDE DECIMAL(10,7),
ADDED_BY BIGINT, (Reference from ADM_USER)
UPDATED_BY BIGINT, (Reference from ADM_USER)
DATE_CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
DATE_UPDATED DATETIME DEFAULT CURRENT_TIMESTAMP,
);
